[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
ms = "ms.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/ms/"]

[project]
name = "ms"
version = "0.0.3"
requires-python = ">=3.12.13"
description = "Based Music Server"
dependencies = [
    "mutagen",
    "textual",
    "python-vlc"
]
