[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
mu = "mu.main:main"
muc = "muc.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/mu/", "src/muc/"]

[tool.ruff]
src = ["src"]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP"]

[project]
name = "mu"
version = "0.1.3"
requires-python = ">=3.12.13"
description = "your personal music library"
dependencies = ["mutagen", "textual", "textual-image", "pillow", "python-vlc"]
