[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
ms = "ms.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/ms/"]

[project]
name = "ms"
version = "1.0.0"
description = "Scarlett Music Server"
dependencies = [
    "requests",
    "dotenv",
    "spotipy",
    "mutagen",
    "yt_dlp"
]
